real_data:
  - subfolder: "2023_reprocess"
    root_path: "/eos/experiment/sndlhc/convertedData/physics/2023_reprocess/"
  - subfolder: "2022"
    root_path: "/eos/experiment/sndlhc/convertedData/physics/2022/"

MC_neutrino:
  - subfolder: "volMuFilter_20fb-1"
    root_path: "/eos/experiment/sndlhc/MonteCarlo/Neutrinos/Genie/sndlhc_13TeV_down_volMuFilter_20fb-1_SNDG18_02a_01_000"
  - subfolder: "volTarget_100fb-1"
    root_path: "/eos/experiment/sndlhc/MonteCarlo/Neutrinos/Genie/sndlhc_13TeV_down_volTarget_100fb-1_SNDG18_02a_01_000"

MC_kaon:
  - subfolder: "FTFP_BERT"
    root_path: "/eos/experiment/sndlhc/MonteCarlo/NeutralHadrons/FTFP_BERT/kaons/"
  - subfolder: "QGSP_BERT_HP_PEN"
    root_path: "/eos/experiment/sndlhc/MonteCarlo/NeutralHadrons/QGSP_BERT_HP_PEN/kaons/"

MC_neutron:
  - subfolder: "FTFP_BERT"
    root_path: "/eos/experiment/sndlhc/MonteCarlo/NeutralHadrons/FTFP_BERT/neutrons/"
  - subfolder: "QGSP_BERT_HP_PEN"
    root_path: "/eos/experiment/sndlhc/MonteCarlo/NeutralHadrons/QGSP_BERT_HP_PEN/neutrons/"

MC_muon:
  - subfolder: "down"
    root_path: "/eos/experiment//sndlhc/MonteCarlo/MuonBackground/muons_down"
  - subfolder: "up"
    root_path: "/eos/experiment//sndlhc/MonteCarlo/MuonBackground/muons_up"
  - subfolder: "horizontal"
    root_path: "/eos/experiment//sndlhc/MonteCarlo/MuonBackground/muons_horizontal"
