
executable = /afs/cern.ch/user/z/zhibin/work/snd-ml/data/convertedData/condor_scripts/run_vm_eff.sh
arguments = $(input_dir) 
log=/afs/cern.ch/user/z/zhibin/work/snd-ml/data/convertedData/condor_scripts/log/vm_eff_$(partition)_$(ClusterId).$(ProcId).log
output=/afs/cern.ch/user/z/zhibin/work/snd-ml/data/convertedData/condor_scripts/output/vm_eff_$(partition)_$(ClusterId).$(ProcId).log
error=/afs/cern.ch/user/z/zhibin/work/snd-ml/data/convertedData/condor_scripts/error/vm_eff_$(partition)_$(ClusterId).$(ProcId).log

should_transfer_files = Yes
request_CPUs = 1
#+AccountingGroup = "group_u_SNDLHC.users"
+JobFlavour = "longlunch"
requirements = (TARGET.OpSysAndVer =?= "AlmaLinux9")
queue partition, input_dir from /afs/cern.ch/user/z/zhibin/work/snd-ml/data/convertedData/condor_scripts/vm_eff_test.list