executable              = pred_run.sh
arguments               = $(partition)
output                  = output/pred.$(ClusterId).$(ProcId).out
error                   = error/pred.$(ClusterId).$(ProcId).err
log                     = log/pred.$(ClusterId).log

should_transfer_files   = YES
RequestCpus = 1
#request_GPUs = 1
+JobFlavour = "longlunch"
queue partition from /afs/cern.ch/user/z/zhibin/work/snd-ml/src/condor/pred.list