executable              = plot.sh
arguments               = $(model) $(signal) $(initial) $(begin)
output                  = output/plot.$(ClusterId).$(ProcId).out
error                   = error/plot.$(ClusterId).$(ProcId).err
log                     = log/plot.$(ClusterId).log

should_transfer_files   = YES
RequestCpus = 2
+JobFlavour = "tomorrow"
queue model,signal,initial,begin from /afs/cern.ch/user/z/zhibin/work/snd-ml/src/condor/plot_model.list