executable              = test_model.sh
arguments               = $(model)
output                  = output/test_model.$(ClusterId).$(ProcId).out
error                   = error/test_model.$(ClusterId).$(ProcId).err
log                     = log/test_model.$(ClusterId).log

should_transfer_files   = YES
request_GPUs = 1
RequestCpus = 8
+JobFlavour = "workday"
queue model from /afs/cern.ch/user/z/zhibin/work/snd-ml/src/condor/test_model.list