executable              = train.sh
arguments               = $(model)
output                  = output/train.$(ClusterId).$(ProcId).out
error                   = error/train.$(ClusterId).$(ProcId).err
log                     = log/train.$(ClusterId).log

should_transfer_files   = YES
request_GPUs = 1
RequestCpus = 8
+JobFlavour = "workday"
queue model from /afs/cern.ch/user/z/zhibin/work/snd-ml/src/condor/train_model.list
