jobscript: "grid-jobscript.sh"
cluster: "grid-submit.py"
cluster-status: "grid-status.py"
max-jobs-per-second: 25
max-status-checks-per-second: 25
restart-times: 0
local-cores: 10
jobs: 400
verbose: false
