jobscript: "grid-jobscript.sh"
executor: "cluster-generic"
cluster-generic-status-cmd: "grid-status.py"
cluster-generic-submit-cmd: "grid-submit.py"
max-jobs-per-second: 25
max-status-checks-per-second: 25
restart-times: 0
local-cores: 10
jobs: 400
verbose: false