jobscript: "grid-jobscript.sh"
executor: "cluster-generic"
cluster-generic-status-cmd: "grid-status.py"
cluster-generic-submit-cmd: "grid-submit.py"
max-jobs-per-second: 50
max-status-checks-per-second: 50
restart-times: 0
local-cores: 10
jobs: 500
verbose: false