ModelCheckpoint:
  mode: min
  monitor: val_loss
  save_last: true
  save_top_k: 1
aggregation: mean_sum
aggs:
- add
- max
- mean
batch_size:
  test: 1024
  train: 1024
  val: 1024
batchnorm: true
check_val_every_n_epoch: 5
class_weights:
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
concat_all_layers: false
data: /eos/user/z/zhibin/sndData/converted/pt
emb_dims: 16
factor: 0.93
feature_dropout: 0.0
feature_set:
- Hits.detType
- Hits.orientation
- Hits.x1
- Hits.y1
- Hits.z1
- Hits.x2
- Hits.y2
- Hits.z2
final_dropout: 0.1
global_feature_channels: 6
global_feature_set:
- RecoMuon.px
- RecoMuon.py
- RecoMuon.pz
- RecoMuon.x
- RecoMuon.y
- RecoMuon.z
graph_construction: null
grav_weight: 3.0
hidden: 64
hidden_activation: ReLU
knn: null
layer_shape: pyramid
layernorm: false
logger:
  entity: '1246249540'
  name: baseline_muon
  project: snd-ml-GravNet
  save_dir: /afs/cern.ch/user/z/zhibin/work/snd-ml/log/snd-ml-GravNet/
  version: 11
lr: 0.003
max_epochs: 200
max_knn: 16
n_graph_iters: 5
n_grav_heads: 5
nb_classes: 7
nb_decoder_layer: 3
nb_encoder_layer: 3
nb_feature_layer: 3
nb_spatial_layer: 3
norm_embedding: false
norm_hidden: true
output_activation: null
patience: 2
r: 1.0
rand_k: null
self_loop: true
spatial_channels: 8
spatial_dropout: 0.0
use_event_feature: false
use_weights: false
weight_type: weight
